/**
 * The TypeScript manifest contract against the real Python engine's.
 *
 * src/core/manifest.ts reimplements `agent_sparring.manifest.parse_manifest`
 * and `manifest_digest` so the extension can ask the one question that settles
 * whether a manifest on disk belongs to a run: *does it digest to the
 * `plan_digest` the engine recorded?* That makes the two implementations one
 * contract with two authors, and the failure mode of a divergence is silent —
 * a run whose real manifest is refused loses its stage list, its journey and
 * the historical membership of every finished stage, and says only "not
 * recorded here".
 *
 * So the engine is the oracle, never a reading of it. `manifestVectors.ts`
 * holds the inputs, `manifestParityPins.ts` holds what the engine answered for
 * them (generated by scripts/generate-manifest-pins.js), and this file checks
 * both directions:
 *
 *  - **always**, with no Python present: the TypeScript parser must agree with
 *    every pin, on acceptance *and* on the digest bytes;
 *  - **whenever the engine is importable**: the pins themselves are re-run
 *    against it, so a deliberate change to the engine's contract — or an
 *    accidental one — shows up here rather than in a run that has already lost
 *    its stages.
 *
 * Point it at an engine with `AGENT_SPARRING_SRC=<agent-sparring>/src`, and
 * optionally `PYTHON=<interpreter>`. Without those the differential half skips
 * and says so; the pinned half still runs, which is what keeps CI honest.
 */

import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import * as path from "node:path";
import { describe, it } from "node:test";
import { parseExecutionManifest, pythonStrip } from "../core/manifest";
import { MANIFEST_PARITY_PINS } from "./manifestParityPins";
import { MANIFEST_VECTORS, type ManifestVectorResult } from "./manifestVectors";

const pins = new Map(MANIFEST_PARITY_PINS.map((pin) => [pin.name, pin]));

/**
 * What the extension answers for one vector, in the shape the probe reports.
 *
 * `parseExecutionManifest` deliberately collapses "the engine would refuse
 * this" and "the engine would accept it and then fail to digest it" into one
 * `undefined`, because the extension's only use for a parse is the digest: a
 * manifest with no digest can never be shown to be a recorded run's, whichever
 * of the two reasons applies. So acceptance is compared only where a digest
 * exists, and the no-digest cases are compared as exactly that.
 */
function answerFor(json: string): { digest?: string } {
  const parsed = parseExecutionManifest(json);
  return parsed ? { digest: parsed.digest } : {};
}

/** The digest the engine produced, or undefined when it refused or raised. */
function engineDigest(pin: ManifestVectorResult): string | undefined {
  return pin.digest;
}

describe("execution manifest: parity with the engine's own contract", () => {
  it("has a pin for every vector, and no pin without a vector", () => {
    const names = MANIFEST_VECTORS.map((vector) => vector.name);
    assert.deepEqual(
      [...pins.keys()].sort(),
      [...names].sort(),
      "manifestParityPins.ts is out of step with manifestVectors.ts; regenerate it with scripts/generate-manifest-pins.js",
    );
    assert.equal(new Set(names).size, names.length, "vector names must be unique");
  });

  for (const vector of MANIFEST_VECTORS) {
    it(`matches the engine for ${vector.name} — ${vector.why}`, () => {
      const pin = pins.get(vector.name);
      assert.ok(pin, `no pin for ${vector.name}`);
      const ours = answerFor(vector.json);
      assert.equal(
        ours.digest,
        engineDigest(pin),
        `${vector.name}: the extension ${ours.digest ? `digests to ${ours.digest}` : "produces no digest"} while the engine ${
          engineDigest(pin) ? `digests to ${engineDigest(pin)}` : `produces none (${pin.error ?? "refused"})`
        }`,
      );
    });
  }

  it("refuses a digest for a manifest the engine accepts but cannot encode", () => {
    // The one case where "no digest" is not "refused": the engine's parser
    // returns and `str.encode('utf-8')` then raises. The extension must not
    // fill that gap with Node's U+FFFD substitution, which would be a digest
    // only one side can compute.
    const accepted = MANIFEST_VECTORS.filter((vector) => pins.get(vector.name)?.accepted && pins.get(vector.name)?.digest === undefined);
    assert.ok(accepted.length >= 2, "expected the lone-surrogate vectors to be accepted-but-not-digestible");
    for (const vector of accepted) {
      assert.equal(parseExecutionManifest(vector.json), undefined, `${vector.name} must yield no ParsedManifest`);
      assert.match(pins.get(vector.name)?.error ?? "", /UnicodeEncodeError/);
    }
  });
});

describe("pythonStrip", () => {
  it("strips what Python strips and not what only JavaScript strips", () => {
    // The five code points where the two disagree, in both directions.
    assert.equal(pythonStrip("x"), "x", "U+0085 is Python whitespace");
    assert.equal(pythonStrip("x"), "x", "U+001C–U+001F are Python whitespace");
    assert.equal(pythonStrip("﻿x﻿"), "﻿x﻿", "U+FEFF is not Python whitespace");
    assert.equal("﻿x﻿".trim(), "x", "…but trim() removes it, which is the bug this replaces");
    assert.equal("x".trim(), "x", "…and trim() keeps U+0085, which is the bug in the other direction");
  });

  it("agrees with trim() on the whitespace they share", () => {
    for (const shared of ["\t", "\n", "\v", "\f", "\r", " ", " ", " ", " ", " ", " ", " ", " ", " ", "　"]) {
      assert.equal(pythonStrip(`${shared}x${shared}`), "x", `${JSON.stringify(shared)} is whitespace to both`);
    }
  });

  it("leaves interior whitespace and non-whitespace alone", () => {
    assert.equal(pythonStrip("a  b"), "a  b");
    assert.equal(pythonStrip("​x"), "​x", "U+200B ZWSP is whitespace to neither");
    assert.equal(pythonStrip(""), "");
    assert.equal(pythonStrip("   "), "");
  });
});

// ---------------------------------------------------------------------------
// the differential half: the pins re-checked against a live engine
// ---------------------------------------------------------------------------

const ENGINE_SRC = process.env.AGENT_SPARRING_SRC;
const PYTHON = process.env.PYTHON ?? "python3";

function probeEngine(): ManifestVectorResult[] | undefined {
  if (!ENGINE_SRC) {
    return undefined;
  }
  const probe = path.join(__dirname, "..", "..", "scripts", "manifest_probe.py");
  const input = JSON.stringify(MANIFEST_VECTORS.map((vector) => ({ name: vector.name, json: vector.json })));
  try {
    const stdout = execFileSync(PYTHON, [probe], {
      input,
      env: { ...process.env, PYTHONPATH: ENGINE_SRC },
      encoding: "utf8",
      maxBuffer: 64 * 1024 * 1024,
    });
    const parsed = JSON.parse(stdout) as ManifestVectorResult[] | { error: string };
    if (!Array.isArray(parsed)) {
      throw new Error(parsed.error);
    }
    return parsed;
  } catch (error) {
    throw new Error(`AGENT_SPARRING_SRC is set but the engine could not be probed: ${(error as Error).message}`);
  }
}

describe("execution manifest: the pins re-checked against a live engine", () => {
  const live = probeEngine();

  it("was probed, or says why it was not", { skip: live ? false : "set AGENT_SPARRING_SRC=<agent-sparring>/src to run the differential half" }, () => {
    assert.ok(live);
    for (const answer of live) {
      const pin = pins.get(answer.name);
      assert.ok(pin, `the engine answered for ${answer.name}, which has no pin`);
      assert.equal(
        answer.digest,
        pin.digest,
        `${answer.name}: the engine now ${answer.digest ? `digests to ${answer.digest}` : `produces no digest (${answer.error ?? "refused"})`}, but the pin says ${
          pin.digest ?? `none (${pin.error ?? "refused"})`
        }. The engine's manifest contract has moved; regenerate the pins with scripts/generate-manifest-pins.js and review the diff.`,
      );
      assert.equal(answer.accepted, pin.accepted, `${answer.name}: acceptance changed in the engine`);
    }
    assert.equal(live.length, MANIFEST_VECTORS.length);
  });
});
